#!/bin/bash

# ========================================
# Script de déploiement EMS Production
# VPS: 51.75.252.74
# Domaines: attendee.fr, api.attendee.fr
# ========================================

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}   EMS Production Deployment Script${NC}"
echo -e "${GREEN}========================================${NC}"

# Configuration
DEPLOY_DIR="/opt/ems-attendee"
BACKEND_REPO="https://github.com/Rabiegha/attendee-ems-back.git"
FRONTEND_REPO="https://github.com/Rabiegha/attendee-ems-front.git"
BRANCH="main"

# Step 1: Create deployment directory
echo -e "\n${YELLOW}[1/8] Creating deployment directory...${NC}"
sudo mkdir -p "$DEPLOY_DIR"
sudo chown -R debian:debian "$DEPLOY_DIR"
cd "$DEPLOY_DIR"

# Step 2: Clone backend repository
echo -e "\n${YELLOW}[2/8] Cloning backend repository (branch: $BRANCH)...${NC}"
if [ -d "backend" ]; then
    echo "Backend directory exists, pulling latest changes..."
    cd backend
    git fetch origin
    git checkout "$BRANCH"
    git pull origin "$BRANCH"
    cd ..
else
    git clone -b "$BRANCH" "$BACKEND_REPO" backend
fi

# Step 3: Clone frontend repository
echo -e "\n${YELLOW}[3/8] Cloning frontend repository (branch: $BRANCH)...${NC}"
if [ -d "frontend" ]; then
    echo "Frontend directory exists, pulling latest changes..."
    cd frontend
    git fetch origin
    git checkout "$BRANCH"
    git pull origin "$BRANCH"
    cd ..
else
    git clone -b "$BRANCH" "$FRONTEND_REPO" frontend
fi

# Step 4: Load .env.vps configuration
echo -e "\n${YELLOW}[4/8] Loading backend configuration from .env.vps...${NC}"

# Check if .env.vps exists
if [ ! -f "$DEPLOY_DIR/backend/.env.vps" ]; then
    echo -e "${RED}ERROR: .env.vps not found in $DEPLOY_DIR/backend/${NC}"
    echo "Please create .env.vps with all required configuration"
    exit 1
fi

# Copy .env.vps to .env.production
cp "$DEPLOY_DIR/backend/.env.vps" "$DEPLOY_DIR/backend/.env.production"

# Step 5: Generate fresh secrets every time
echo -e "\n${YELLOW}[5/8] Generating fresh secrets...${NC}"

# Generate new secrets
echo "Generating PostgreSQL password..."
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9')

echo "Generating JWT secrets..."
JWT_ACCESS_SECRET=$(openssl rand -base64 64 | tr -d '\n')
JWT_REFRESH_SECRET=$(openssl rand -base64 64 | tr -d '\n')
JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')

# Replace placeholders in .env.production
sed -i "s|AUTOGENERATED_POSTGRES_PASSWORD|${POSTGRES_PASSWORD}|g" "$DEPLOY_DIR/backend/.env.production"
sed -i "s|AUTOGENERATED_JWT_ACCESS_SECRET|${JWT_ACCESS_SECRET}|g" "$DEPLOY_DIR/backend/.env.production"
sed -i "s|AUTOGENERATED_JWT_REFRESH_SECRET|${JWT_REFRESH_SECRET}|g" "$DEPLOY_DIR/backend/.env.production"
sed -i "s|AUTOGENERATED_JWT_SECRET|${JWT_SECRET}|g" "$DEPLOY_DIR/backend/.env.production"

echo -e "${GREEN}✓ All secrets generated and configured${NC}"

# Create .env file for Docker Compose interpolation (Postgres service needs this)
echo "Creating .env for Docker Compose..."
cat > "$DEPLOY_DIR/backend/.env" <<EOF
POSTGRES_USER=ems_prod
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=ems_production
EOF

echo -e "${GREEN}✓ Backend .env.production and .env created with secure secrets${NC}"

# Step 6: Build frontend
echo -e "\n${YELLOW}[6/8] Building frontend for production...${NC}"
cd "$DEPLOY_DIR/frontend"

# Always install dependencies to ensure they are up to date
echo "Installing frontend dependencies..."
npm install

# Build frontend
echo "Building frontend..."
VITE_API_URL=https://api.attendee.fr npm run build

echo -e "${GREEN}✓ Frontend built successfully${NC}"

# Step 7: Copy frontend build to nginx directory
echo -e "\n${YELLOW}[7/8] Preparing frontend for Nginx...${NC}"
mkdir -p "$DEPLOY_DIR/backend/frontend"
cp -r "$DEPLOY_DIR/frontend/dist/"* "$DEPLOY_DIR/backend/frontend/"
echo -e "${GREEN}✓ Frontend files copied${NC}"

# Step 8: Start Docker services with fresh secrets
echo -e "\n${YELLOW}[8/8] Starting Docker services...${NC}"
cd "$DEPLOY_DIR/backend"

# Check if postgres container exists (running or stopped)
POSTGRES_EXISTS=$(docker ps -aq -f name=ems-postgres 2>/dev/null || echo "")

if [ -n "$POSTGRES_EXISTS" ]; then
    echo "Existing PostgreSQL container found, updating password before recreating..."
    
    # Start postgres if not running
    docker compose -f docker-compose.prod.yml up -d postgres 2>/dev/null || true
    sleep 5
    
    # Update password in running PostgreSQL instance
    echo "Updating PostgreSQL password to match new configuration..."
    docker exec -i ems-postgres psql -U ems_prod -d ems_production <<EOF 2>/dev/null || true
ALTER USER ems_prod WITH PASSWORD '${POSTGRES_PASSWORD}';
EOF
    
    echo -e "${GREEN}✓ PostgreSQL password updated${NC}"
fi

# Stop existing containers (keep volumes to preserve data)
echo "Stopping existing containers..."
docker compose -f docker-compose.prod.yml down 2>/dev/null || true

# Start services with fresh build and force recreate containers with new secrets
echo "Starting services with new configuration..."
docker compose -f docker-compose.prod.yml up -d --build --force-recreate

# Wait for database to be ready
echo "Waiting for PostgreSQL to be ready..."
sleep 10

# Check if services are running
echo -e "\n${GREEN}Checking service status:${NC}"
docker ps --filter "name=ems" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"

echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}   Deployment completed successfully!${NC}"
echo -e "${GREEN}========================================${NC}"

echo -e "\n${YELLOW}Next steps:${NC}"
echo "1. Configure DNS records at OVH:"
echo "   - A record: attendee.fr → 51.75.252.74"
echo "   - A record: api.attendee.fr → 51.75.252.74"
echo ""
echo "2. Once DNS is propagated (check with: dig attendee.fr), run:"
echo "   sudo certbot --nginx -d attendee.fr -d www.attendee.fr -d api.attendee.fr"
echo ""
echo "3. Check service status:"
echo "   docker ps"
echo "   docker logs ems-api"
echo "   docker logs ems-nginx"
echo ""
echo -e "${GREEN}Your application will be available at:${NC}"
echo "   - Frontend: https://attendee.fr"
echo "   - API: https://api.attendee.fr"
