FROM node:20-alpine

WORKDIR /usr/src/app

# Dépendances système utiles (bcrypt, etc.)
RUN apk add --no-cache python3 make g++ bash openssl

COPY package*.json ./
RUN npm install

COPY . .

# Generate Prisma client
RUN npx prisma generate

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
