import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedEvents() {
  console.log('ℹ️  Seeding events...');

  // Récupérer l'organisation Acme Corp
  const acmeOrg = await prisma.organization.findFirst({
    where: { slug: 'acme-corp' },
  });

  if (!acmeOrg) {
    console.log(' Organization Acme Corp not found, skipping events seeding');
    return;
  }

  // Créer beaucoup d'événements de test (passés et à venir)
  const events = [
    // ==================== ÉVÉNEMENTS PASSÉS (2024 - Octobre 2025) ====================
    // Janvier 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-01-01',
      name: 'Tech Conference Janvier 2024',
      description: 'Grande conférence technologique du début d\'année.',
      start_at: new Date('2024-01-15T09:00:00Z'),
      end_at: new Date('2024-01-15T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 300,
      location_type: 'physical' as const,
      address_formatted: 'Centre de Conférences, Lyon, France',
      address_street: '10 Rue de la Tech',
      address_city: 'Lyon',
      address_region: 'Auvergne-Rhône-Alpes',
      address_postal_code: '69000',
      address_country: 'France',
      latitude: 45.7640,
      longitude: 4.8357,
    },
    // Février 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-02-01',
      name: 'Webinar Cybersécurité 2024',
      description: 'Formation en ligne sur les menaces cybersécurité.',
      start_at: new Date('2024-02-10T15:00:00Z'),
      end_at: new Date('2024-02-10T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 500,
      location_type: 'online' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-02-02',
      name: 'Meetup Python Février',
      description: 'Rencontre mensuelle des développeurs Python.',
      start_at: new Date('2024-02-20T18:00:00Z'),
      end_at: new Date('2024-02-20T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 60,
      location_type: 'physical' as const,
      address_formatted: 'Station F, Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    // Mars 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-03-01',
      name: 'Workshop React Avancé',
      description: 'Atelier pratique sur React et les hooks avancés.',
      start_at: new Date('2024-03-05T10:00:00Z'),
      end_at: new Date('2024-03-05T16:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 40,
      location_type: 'hybrid' as const,
      address_formatted: 'Ecole 42, Paris, France',
      address_street: '96 Boulevard Bessières',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75017',
      address_country: 'France',
      latitude: 48.8975,
      longitude: 2.3156,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-03-02',
      name: 'Conférence UX/UI Design',
      description: 'Dernières tendances en design d\'interface.',
      start_at: new Date('2024-03-18T09:00:00Z'),
      end_at: new Date('2024-03-18T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 200,
      location_type: 'hybrid' as const,
      address_formatted: 'Design Center, Lyon, France',
      address_street: '25 Rue du Design',
      address_city: 'Lyon',
      address_region: 'Auvergne-Rhône-Alpes',
      address_postal_code: '69000',
      address_country: 'France',
      latitude: 45.7640,
      longitude: 4.8357,
    },
    // Avril 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-04-01',
      name: 'Meetup DevOps Avril',
      description: 'Rencontre mensuelle des professionnels DevOps.',
      start_at: new Date('2024-04-12T18:00:00Z'),
      end_at: new Date('2024-04-12T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 80,
      location_type: 'physical' as const,
      address_formatted: 'Station F, Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-04-02',
      name: 'Formation TypeScript',
      description: 'Formation complète sur TypeScript et ses bonnes pratiques.',
      start_at: new Date('2024-04-22T09:00:00Z'),
      end_at: new Date('2024-04-24T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 35,
      location_type: 'physical' as const,
      address_formatted: 'Tech Academy, Toulouse, France',
      address_street: '15 Rue de l\'Innovation',
      address_city: 'Toulouse',
      address_region: 'Occitanie',
      address_postal_code: '31000',
      address_country: 'France',
      latitude: 43.6047,
      longitude: 1.4442,
    },
    // Mai 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-05-01',
      name: 'Data Science Summit 2024',
      description: 'Sommet annuel sur la science des données et le Big Data.',
      start_at: new Date('2024-05-20T09:00:00Z'),
      end_at: new Date('2024-05-21T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 600,
      location_type: 'hybrid' as const,
      address_formatted: 'Palais des Congrès, Paris, France',
      address_street: '2 Place de la Porte Maillot',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75017',
      address_country: 'France',
      latitude: 48.8784,
      longitude: 2.2834,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-05-02',
      name: 'Webinar Performance Web',
      description: 'Optimisation des performances des applications web.',
      start_at: new Date('2024-05-28T15:00:00Z'),
      end_at: new Date('2024-05-28T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 400,
      location_type: 'online' as const,
    },
    // Juin 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-06-01',
      name: 'Formation Kubernetes Intensive',
      description: 'Formation de 3 jours sur Kubernetes et l\'orchestration.',
      start_at: new Date('2024-06-10T09:00:00Z'),
      end_at: new Date('2024-06-12T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 25,
      location_type: 'physical' as const,
      address_formatted: 'Centre de Formation Tech, Toulouse, France',
      address_street: '15 Rue de l\'Innovation',
      address_city: 'Toulouse',
      address_region: 'Occitanie',
      address_postal_code: '31000',
      address_country: 'France',
      latitude: 43.6047,
      longitude: 1.4442,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-06-02',
      name: 'Meetup JavaScript Juin',
      description: 'Rencontre des développeurs JavaScript.',
      start_at: new Date('2024-06-25T18:30:00Z'),
      end_at: new Date('2024-06-25T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 75,
      location_type: 'hybrid' as const,
      address_formatted: 'Innovation Hub, Bordeaux, France',
      address_street: '20 Quai des Chartrons',
      address_city: 'Bordeaux',
      address_region: 'Nouvelle-Aquitaine',
      address_postal_code: '33000',
      address_country: 'France',
      latitude: 44.8378,
      longitude: -0.5792,
    },
    // Juillet 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-07-01',
      name: 'Hackathon Innovation 2024',
      description: 'Marathon de programmation de 48h.',
      start_at: new Date('2024-07-05T09:00:00Z'),
      end_at: new Date('2024-07-07T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 150,
      location_type: 'physical' as const,
      address_formatted: 'Campus Innovation, Sophia Antipolis, France',
      address_street: '20 Route des Lucioles',
      address_city: 'Sophia Antipolis',
      address_region: 'Provence-Alpes-Côte d\'Azur',
      address_postal_code: '06410',
      address_country: 'France',
      latitude: 43.6148,
      longitude: 7.0702,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-07-02',
      name: 'Conférence Serverless',
      description: 'Architecture serverless et cloud functions.',
      start_at: new Date('2024-07-22T09:00:00Z'),
      end_at: new Date('2024-07-22T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 250,
      location_type: 'hybrid' as const,
      address_formatted: 'Tech Center, Lille, France',
      address_street: '12 Avenue des Développeurs',
      address_city: 'Lille',
      address_region: 'Hauts-de-France',
      address_postal_code: '59000',
      address_country: 'France',
      latitude: 50.6292,
      longitude: 3.0573,
    },
    // Août 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-08-01',
      name: 'Webinar Développement Mobile',
      description: 'Les tendances du développement mobile en 2024.',
      start_at: new Date('2024-08-15T14:00:00Z'),
      end_at: new Date('2024-08-15T16:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 1000,
      location_type: 'online' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-08-02',
      name: 'Workshop Flutter',
      description: 'Développement d\'applications mobiles avec Flutter.',
      start_at: new Date('2024-08-28T10:00:00Z'),
      end_at: new Date('2024-08-28T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 45,
      location_type: 'physical' as const,
      address_formatted: 'Mobile Lab, Rennes, France',
      address_street: '8 Rue de l\'Innovation',
      address_city: 'Rennes',
      address_region: 'Bretagne',
      address_postal_code: '35000',
      address_country: 'France',
      latitude: 48.1173,
      longitude: -1.6778,
    },
    // Septembre 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-09-01',
      name: 'Conférence Agile France',
      description: 'Conférence sur les méthodes agiles et Scrum.',
      start_at: new Date('2024-09-10T09:00:00Z'),
      end_at: new Date('2024-09-11T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 400,
      location_type: 'hybrid' as const,
      address_formatted: 'Centre des Congrès, Nantes, France',
      address_street: '5 Rue de Valmy',
      address_city: 'Nantes',
      address_region: 'Pays de la Loire',
      address_postal_code: '44000',
      address_country: 'France',
      latitude: 47.2184,
      longitude: -1.5536,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-09-02',
      name: 'Formation Docker & CI/CD',
      description: 'Docker et intégration continue.',
      start_at: new Date('2024-09-23T09:00:00Z'),
      end_at: new Date('2024-09-25T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 30,
      location_type: 'physical' as const,
      address_formatted: 'DevOps School, Strasbourg, France',
      address_street: '18 Rue du Port du Rhin',
      address_city: 'Strasbourg',
      address_region: 'Grand Est',
      address_postal_code: '67000',
      address_country: 'France',
      latitude: 48.5734,
      longitude: 7.7521,
    },
    // Octobre 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-10-01',
      name: 'Meetup Blockchain Octobre',
      description: 'Discussion sur la blockchain et les cryptomonnaies.',
      start_at: new Date('2024-10-08T18:30:00Z'),
      end_at: new Date('2024-10-08T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 60,
      location_type: 'physical' as const,
      address_formatted: 'Incubateur Tech, Marseille, France',
      address_street: '30 Avenue du Prado',
      address_city: 'Marseille',
      address_region: 'Provence-Alpes-Côte d\'Azur',
      address_postal_code: '13006',
      address_country: 'France',
      latitude: 43.2965,
      longitude: 5.3698,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-10-02',
      name: 'Webinar GraphQL',
      description: 'Introduction à GraphQL et Apollo.',
      start_at: new Date('2024-10-22T15:00:00Z'),
      end_at: new Date('2024-10-22T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 500,
      location_type: 'online' as const,
    },
    // Novembre 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-11-01',
      name: 'Workshop Node.js Avancé',
      description: 'Techniques avancées avec Node.js et Express.',
      start_at: new Date('2024-11-12T10:00:00Z'),
      end_at: new Date('2024-11-12T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 40,
      location_type: 'physical' as const,
      address_formatted: 'Station F, Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-11-02',
      name: 'Conférence Testing & QA',
      description: 'Tests automatisés et assurance qualité.',
      start_at: new Date('2024-11-26T09:00:00Z'),
      end_at: new Date('2024-11-26T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 180,
      location_type: 'hybrid' as const,
      address_formatted: 'Quality Center, Lyon, France',
      address_street: '10 Rue de la Tech',
      address_city: 'Lyon',
      address_region: 'Auvergne-Rhône-Alpes',
      address_postal_code: '69000',
      address_country: 'France',
      latitude: 45.7640,
      longitude: 4.8357,
    },
    // Décembre 2024
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-12-01',
      name: 'Hackathon Noël 2024',
      description: 'Hackathon de fin d\'année.',
      start_at: new Date('2024-12-14T09:00:00Z'),
      end_at: new Date('2024-12-15T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 100,
      location_type: 'physical' as const,
      address_formatted: 'Innovation Campus, Nice, France',
      address_street: '25 Promenade des Anglais',
      address_city: 'Nice',
      address_region: 'Provence-Alpes-Côte d\'Azur',
      address_postal_code: '06000',
      address_country: 'France',
      latitude: 43.7102,
      longitude: 7.2620,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2024-12-02',
      name: 'Webinar Sécurité 2024',
      description: 'Bilan des menaces cybersécurité 2024.',
      start_at: new Date('2024-12-28T14:00:00Z'),
      end_at: new Date('2024-12-28T16:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 700,
      location_type: 'online' as const,
    },
    // Janvier - Octobre 2025
    {
      org_id: acmeOrg.id,
      code: 'PAST-2025-01-01',
      name: 'New Year Tech Meetup',
      description: 'Premier meetup de l\'année 2025.',
      start_at: new Date('2025-01-15T18:00:00Z'),
      end_at: new Date('2025-01-15T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 90,
      location_type: 'physical' as const,
      address_formatted: 'Station F, Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    {
      org_id: acmeOrg.id,
      code: 'PAST-2025-10-01',
      name: 'Conférence Automne Tech',
      description: 'Grande conférence d\'automne.',
      start_at: new Date('2025-10-15T09:00:00Z'),
      end_at: new Date('2025-10-16T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 450,
      location_type: 'hybrid' as const,
      address_formatted: 'Palais des Congrès, Paris, France',
      address_street: '2 Place de la Porte Maillot',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75017',
      address_country: 'France',
      latitude: 48.8784,
      longitude: 2.2834,
    },

    // ==================== ÉVÉNEMENTS À VENIR (Novembre 2025 et après) ====================
    // ÉVÉNEMENT AUJOURD'HUI (2 novembre 2025)
    {
      org_id: acmeOrg.id,
      code: 'TODAY-2025-11-02',
      name: '🔥 Workshop Live Coding AUJOURD\'HUI',
      description: 'Atelier de live coding en direct - Session spéciale du jour !',
      start_at: new Date('2025-11-02T14:00:00Z'),
      end_at: new Date('2025-11-02T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 30,
      location_type: 'hybrid' as const,
      address_formatted: 'Station F, 5 Parvis Alan Turing, 75013 Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    // Événements proches (dans les prochains jours)
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-11-05',
      name: 'Meetup React Native',
      description: 'Rencontre des développeurs React Native de Paris.',
      start_at: new Date('2025-11-05T18:30:00Z'),
      end_at: new Date('2025-11-05T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 50,
      location_type: 'physical' as const,
      address_formatted: 'Station F, Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-11-08',
      name: 'Formation TypeScript Avancé',
      description: 'Formation approfondie sur TypeScript et ses patterns avancés.',
      start_at: new Date('2025-11-08T09:00:00Z'),
      end_at: new Date('2025-11-08T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 25,
      location_type: 'physical' as const,
      address_formatted: 'Tech Academy, Lyon, France',
      address_street: '10 Rue de la Tech',
      address_city: 'Lyon',
      address_region: 'Auvergne-Rhône-Alpes',
      address_postal_code: '69000',
      address_country: 'France',
      latitude: 45.7640,
      longitude: 4.8357,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-11-01',
      name: 'Tech Summit 2025',
      description: 'Conférence annuelle sur les technologies émergentes et l\'innovation.',
      start_at: new Date('2025-11-15T09:00:00Z'),
      end_at: new Date('2025-11-15T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 500,
      location_type: 'hybrid' as const,
      address_formatted: 'Palais des Congrès, 2 Place de la Porte Maillot, 75017 Paris, France',
      address_street: '2 Place de la Porte Maillot',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75017',
      address_country: 'France',
      latitude: 48.8784,
      longitude: 2.2834,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-11-02',
      name: 'Workshop IA Novembre 2025',
      description: 'Atelier sur l\'intelligence artificielle générative.',
      start_at: new Date('2025-11-20T10:00:00Z'),
      end_at: new Date('2025-11-20T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 50,
      location_type: 'physical' as const,
      address_formatted: 'Station F, 5 Parvis Alan Turing, 75013 Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-11-03',
      name: 'Webinar Cloud Native',
      description: 'Architecture cloud-native et microservices.',
      start_at: new Date('2025-11-25T16:00:00Z'),
      end_at: new Date('2025-11-25T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 800,
      location_type: 'online' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-12-01',
      name: 'Workshop IA pour débutants',
      description: 'Formation intensive sur l\'intelligence artificielle et le machine learning.',
      start_at: new Date('2025-12-01T14:00:00Z'),
      end_at: new Date('2025-12-01T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 50,
      location_type: 'physical' as const,
      address_formatted: 'Station F, 5 Parvis Alan Turing, 75013 Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-12-02',
      name: 'Meetup React Décembre',
      description: 'Rencontre mensuelle des développeurs React.',
      start_at: new Date('2025-12-10T18:00:00Z'),
      end_at: new Date('2025-12-10T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 70,
      location_type: 'hybrid' as const,
      address_formatted: 'Tech Hub, Lyon, France',
      address_street: '10 Rue de la Tech',
      address_city: 'Lyon',
      address_region: 'Auvergne-Rhône-Alpes',
      address_postal_code: '69000',
      address_country: 'France',
      latitude: 45.7640,
      longitude: 4.8357,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-12-03',
      name: 'Formation Docker & Containers',
      description: 'Formation complète sur Docker et la conteneurisation.',
      start_at: new Date('2025-12-15T09:00:00Z'),
      end_at: new Date('2025-12-17T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 30,
      location_type: 'physical' as const,
      address_formatted: 'Centre Formation, Bordeaux, France',
      address_street: '25 Rue du Code',
      address_city: 'Bordeaux',
      address_region: 'Nouvelle-Aquitaine',
      address_postal_code: '33000',
      address_country: 'France',
      latitude: 44.8378,
      longitude: -0.5792,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2025-12-04',
      name: 'Webinar Sécurité Fin 2025',
      description: 'Bilan sécurité et perspectives 2026.',
      start_at: new Date('2025-12-22T15:00:00Z'),
      end_at: new Date('2025-12-22T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 600,
      location_type: 'online' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-01-01',
      name: 'Conférence Sécurité 2026',
      description: 'Conférence sur la sécurité informatique et les bonnes pratiques.',
      start_at: new Date('2026-01-20T09:00:00Z'),
      end_at: new Date('2026-01-21T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 350,
      location_type: 'hybrid' as const,
      address_formatted: 'Palais des Congrès, Paris, France',
      address_street: '2 Place de la Porte Maillot',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75017',
      address_country: 'France',
      latitude: 48.8784,
      longitude: 2.2834,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-02-01',
      name: 'Hackathon FinTech 2026',
      description: 'Hackathon dédié aux innovations dans la finance.',
      start_at: new Date('2026-02-14T10:00:00Z'),
      end_at: new Date('2026-02-16T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 120,
      location_type: 'physical' as const,
      address_formatted: 'Station F, Paris, France',
      address_street: '5 Parvis Alan Turing',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75013',
      address_country: 'France',
      latitude: 48.8323,
      longitude: 2.3730,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-02-02',
      name: 'Webinar GraphQL Avancé',
      description: 'Techniques avancées avec GraphQL et Apollo.',
      start_at: new Date('2026-02-25T15:00:00Z'),
      end_at: new Date('2026-02-25T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 600,
      location_type: 'online' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-03-01',
      name: 'Workshop Rust Programming',
      description: 'Développement système avec Rust.',
      start_at: new Date('2026-03-10T10:00:00Z'),
      end_at: new Date('2026-03-10T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 35,
      location_type: 'physical' as const,
      address_formatted: 'Tech Lab, Toulouse, France',
      address_street: '15 Rue de l\'Innovation',
      address_city: 'Toulouse',
      address_region: 'Occitanie',
      address_postal_code: '31000',
      address_country: 'France',
      latitude: 43.6047,
      longitude: 1.4442,
    },
    {
      org_id: acmeOrg.id,
      code: 'DRAFT-EVENT-2026',
      name: 'Future Conference 2026 (Draft)',
      description: 'Événement en cours de préparation pour 2026.',
      start_at: new Date('2026-03-20T10:00:00Z'),
      end_at: new Date('2026-03-20T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'draft' as const,
      capacity: 300,
      location_type: 'physical' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-04-01',
      name: 'Cloud Summit Europe 2026',
      description: 'Le plus grand sommet européen sur le cloud computing.',
      start_at: new Date('2026-04-15T09:00:00Z'),
      end_at: new Date('2026-04-17T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 1200,
      location_type: 'hybrid' as const,
      address_formatted: 'Paris Expo, Porte de Versailles, Paris, France',
      address_street: '1 Place de la Porte de Versailles',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75015',
      address_country: 'France',
      latitude: 48.8337,
      longitude: 2.2865,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-04-02',
      name: 'Meetup Flutter Avril',
      description: 'Rencontre des développeurs Flutter.',
      start_at: new Date('2026-04-22T18:00:00Z'),
      end_at: new Date('2026-04-22T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 65,
      location_type: 'hybrid' as const,
      address_formatted: 'Mobile Hub, Rennes, France',
      address_street: '8 Rue de l\'Innovation',
      address_city: 'Rennes',
      address_region: 'Bretagne',
      address_postal_code: '35000',
      address_country: 'France',
      latitude: 48.1173,
      longitude: -1.6778,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-05-01',
      name: 'Workshop Vue.js 3.0',
      description: 'Atelier pratique sur Vue.js 3.0 et Composition API.',
      start_at: new Date('2026-05-10T10:00:00Z'),
      end_at: new Date('2026-05-10T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 45,
      location_type: 'physical' as const,
      address_formatted: 'Tech School, Lille, France',
      address_street: '12 Avenue des Développeurs',
      address_city: 'Lille',
      address_region: 'Hauts-de-France',
      address_postal_code: '59000',
      address_country: 'France',
      latitude: 50.6292,
      longitude: 3.0573,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-05-02',
      name: 'Formation Python Data Science',
      description: 'Formation intensive Python pour la data science.',
      start_at: new Date('2026-05-18T09:00:00Z'),
      end_at: new Date('2026-05-20T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 28,
      location_type: 'physical' as const,
      address_formatted: 'Data Academy, Lyon, France',
      address_street: '10 Rue de la Tech',
      address_city: 'Lyon',
      address_region: 'Auvergne-Rhône-Alpes',
      address_postal_code: '69000',
      address_country: 'France',
      latitude: 45.7640,
      longitude: 4.8357,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-05-03',
      name: 'Webinar Microservices',
      description: 'Architecture microservices et patterns.',
      start_at: new Date('2026-05-28T15:00:00Z'),
      end_at: new Date('2026-05-28T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 550,
      location_type: 'online' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-06-01',
      name: 'AI & Machine Learning Conference',
      description: 'Conférence internationale sur l\'IA et le ML.',
      start_at: new Date('2026-06-08T09:00:00Z'),
      end_at: new Date('2026-06-10T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 800,
      location_type: 'hybrid' as const,
      address_formatted: 'Palais des Congrès, Paris, France',
      address_street: '2 Place de la Porte Maillot',
      address_city: 'Paris',
      address_region: 'Île-de-France',
      address_postal_code: '75017',
      address_country: 'France',
      latitude: 48.8784,
      longitude: 2.2834,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-06-02',
      name: 'Hackathon Summer 2026',
      description: 'Hackathon d\'été sur les technologies vertes.',
      start_at: new Date('2026-06-20T09:00:00Z'),
      end_at: new Date('2026-06-22T18:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 140,
      location_type: 'physical' as const,
      address_formatted: 'Green Tech Campus, Nantes, France',
      address_street: '5 Rue de Valmy',
      address_city: 'Nantes',
      address_region: 'Pays de la Loire',
      address_postal_code: '44000',
      address_country: 'France',
      latitude: 47.2184,
      longitude: -1.5536,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-07-01',
      name: 'Workshop DevOps Avancé',
      description: 'Techniques avancées DevOps et GitOps.',
      start_at: new Date('2026-07-08T10:00:00Z'),
      end_at: new Date('2026-07-08T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 42,
      location_type: 'physical' as const,
      address_formatted: 'DevOps Center, Marseille, France',
      address_street: '30 Avenue du Prado',
      address_city: 'Marseille',
      address_region: 'Provence-Alpes-Côte d\'Azur',
      address_postal_code: '13006',
      address_country: 'France',
      latitude: 43.2965,
      longitude: 5.3698,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-07-02',
      name: 'Conférence Web Performance',
      description: 'Optimisation des performances web.',
      start_at: new Date('2026-07-22T09:00:00Z'),
      end_at: new Date('2026-07-22T17:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 280,
      location_type: 'hybrid' as const,
      address_formatted: 'Tech Center, Bordeaux, France',
      address_street: '25 Rue du Code',
      address_city: 'Bordeaux',
      address_region: 'Nouvelle-Aquitaine',
      address_postal_code: '33000',
      address_country: 'France',
      latitude: 44.8378,
      longitude: -0.5792,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-08-01',
      name: 'Webinar Testing Moderne',
      description: 'Tests automatisés et TDD.',
      start_at: new Date('2026-08-12T14:00:00Z'),
      end_at: new Date('2026-08-12T16:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 480,
      location_type: 'online' as const,
    },
    {
      org_id: acmeOrg.id,
      code: 'FUTURE-2026-08-02',
      name: 'Meetup Golang Août',
      description: 'Rencontre des développeurs Go.',
      start_at: new Date('2026-08-26T18:00:00Z'),
      end_at: new Date('2026-08-26T21:00:00Z'),
      timezone: 'Europe/Paris',
      status: 'published' as const,
      capacity: 58,
      location_type: 'physical' as const,
      address_formatted: 'Go Hub, Strasbourg, France',
      address_street: '18 Rue du Port du Rhin',
      address_city: 'Strasbourg',
      address_region: 'Grand Est',
      address_postal_code: '67000',
      address_country: 'France',
      latitude: 48.5734,
      longitude: 7.7521,
    },
  ];

  const createdEvents = [];
  for (const eventData of events) {
    const existingEvent = await prisma.event.findFirst({
      where: {
        org_id: eventData.org_id,
        code: eventData.code,
      },
    });

    if (existingEvent) {
      console.log(`✅ Event already exists: ${eventData.name}`);
      createdEvents.push(existingEvent);
      continue;
    }

    const event = await prisma.event.create({
      data: {
        ...eventData,
        // Créer automatiquement EventSetting avec public_token
        settings: {
          create: {
            public_token: `${eventData.code.toLowerCase()}-${Math.random().toString(36).substring(2, 10)}`,
            registration_auto_approve: true,
            allow_checkin_out: true,
            has_event_reminder: false,
            auto_transition_to_active: true,
            auto_transition_to_completed: true,
            registration_fields: [
              { id: 'firstName', name: 'firstName', label: 'Prénom', type: 'text', required: true },
              { id: 'lastName', name: 'lastName', label: 'Nom', type: 'text', required: true },
              { id: 'email', name: 'email', label: 'Email', type: 'email', required: true },
              { id: 'company', name: 'company', label: 'Entreprise', type: 'text', required: false },
              { id: 'jobTitle', name: 'jobTitle', label: 'Fonction', type: 'text', required: false },
            ],
          },
        },
      },
      include: {
        settings: true,
      },
    });

    console.log(`✅ ✓ Event: ${event.name} (${event.code})`);
    createdEvents.push(event);
  }

  console.log(`✅ Total events created/updated: ${createdEvents.length}`);
  return createdEvents;
}

